name: Delete all files older than 2 days (excluding workflows)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove files older than 2 days (excluding workflows)
        run: |
          # Find and delete all files older than 2 days, excluding .github/workflows
          echo "Removing files older than 2 days, excluding workflow files..."

          # Get a list of files changed in the last 2 days
          files=$(git log --since="2 days ago" --pretty=format: --name-only | sort -u)

          # Exclude workflow files by filtering out anything in .github/workflows
          filtered_files=$(echo "$files" | grep -v "^\.github/workflows/")

          if [ -z "$filtered_files" ]; then
            echo "No files to delete."
          else
            echo "$filtered_files" > files-to-delete.txt
            cat files-to-delete.txt
            while IFS= read -r file; do
              git rm "$file" || echo "Failed to remove $file"
            done < files-to-delete.txt
          fi

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "d5user"
          git config --global user.email "d5.softtradeinfotech@gmail.com"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/d5user/WhatsappNew.git
          
          git status
          git add .
          git commit -m "Deleted files older than 2 days, excluding workflows" || echo "No changes to commit"
          git push origin main
